version: '3'
services:
  subset-font:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./subset-gf-icons:/app/subset-gf-icons
      - ./material-design-icons:/app/material-design-icons
    working_dir: /app/subset-gf-icons
