name: "Subset Material Symbols"

on:
  workflow_dispatch:
  push:
    branches:
      - actions
    # paths:
    #   - icons.ts

jobs:
  subset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: rsheeter/subset-gf-icons
          path: subset-gf-icons
      - uses: actions/checkout@v4
        with:
          repository: google/material-design-icons
          path: material-design-icons
          sparse-checkout: variablefont
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        working-directory: ./subset-gf-icons
        run: |
          pip install -e .
      - name: Run subset
        working-directory: ./subset-gf-icons
        run: |
          icons_file_path="../icons"
          echo "import { icons } from '$icons_file_path'; console.log(JSON.stringify(icons, null, 2));" \
          | npx --yes ts-node \
          | jq -r 'join(" ")' \
          | xargs subset_gf_icons --flavor woff2 ../material-design-icons/variablefont/MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf
      - name: Copy subset font file
        run: |
          mkdir -p ./font
          cp ./material-design-icons/variablefont/MaterialSymbolsRounded[FILL,GRAD,opsz,wght]-subset.woff2 ./font/MaterialSymbolsRounded-subset.woff2
      - name: Commit files
        run: |
          git config --local user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git config --local user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git add font
          git commit -m "Add subset font file"
      # - name: Push changes
      #   run: |
      #     git push origin HEAD
