name: "Subset Material Symbols"

on:
  workflow_dispatch:
  push:
    # paths:
    #   - icons.ts

jobs:
  subset:
    runs-on: ubuntu-latest
    env:
      SUBSET_GF_ICONS_DIR: subset-gf-icons
      MATERIAL_DESIGN_ICONS_DIR: material-design-icons
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: rsheeter/subset-gf-icons
          path: ${{ env.SUBSET_GF_ICONS_DIR }}
      - uses: actions/checkout@v4
        with:
          repository: google/material-design-icons
          path: ${{ env.MATERIAL_DESIGN_ICONS_DIR }}
          sparse-checkout: variablefont
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        working-directory: ./${{ env.SUBSET_GF_ICONS_DIR }}
        run: |
          pip install -e .
      - name: Run subset
        working-directory: ./${{ env.SUBSET_GF_ICONS_DIR }}
        run: |
          icons_file_path="../icons"
          echo "import { icons } from '$icons_file_path'; console.log(JSON.stringify(icons, null, 2));" \
          | npx --yes ts-node \
          | jq -r 'join(" ")' \
          | xargs subset_gf_icons --flavor woff2 ../${{ env.MATERIAL_DESIGN_ICONS_DIR }}/variablefont/MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf
      - name: Copy subset font file
        run: |
          mkdir -p ./font
          cp ./${{ env.MATERIAL_DESIGN_ICONS_DIR }}/variablefont/MaterialSymbolsRounded[FILL,GRAD,opsz,wght]-subset.woff2 ./font/MaterialSymbolsRounded-subset.woff2
      - name: Commit files
        run: |
          git config --local user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git config --local user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git add font
          git commit -m "Add subset font file"
      # - name: Push changes
      #   run: |
      #     git push origin HEAD
